# Generated by Django 4.1 on 2022-08-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                (
                    "sub_title",
                    models.CharField(blank=True, max_length=100, verbose_name="부제목"),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("create", models.DateTimeField(auto_now_add=True, verbose_name="작성일")),
                (
                    "room_password",
                    models.CharField(blank=True, max_length=5, verbose_name="방비밀번호"),
                ),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "room_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="방장",
                    ),
                ),
            ],
            options={
                "verbose_name": "room 목록",
                "verbose_name_plural": "room 목록",
            },
        ),
    ]
