# Generated by Django 4.1 on 2022-10-04 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=200, verbose_name="C_comment")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="C_created"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="C_article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "db_table": "room_comment",
            },
        ),
        migrations.CreateModel(
            name="Room_group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="G_title")),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="G_subtitle"
                    ),
                ),
                ("content", models.TextField(verbose_name="G_content")),
                (
                    "create",
                    models.DateTimeField(auto_now_add=True, verbose_name="G_create"),
                ),
                (
                    "room_password",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="G_roompassword"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "room_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="G_room_owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "group ",
                "verbose_name_plural": "Group",
            },
        ),
        migrations.CreateModel(
            name="Room_member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="M_created"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room_group",
                        verbose_name="M_group",
                    ),
                ),
                (
                    "join_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="M_joinuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "db_table": "room_member",
            },
        ),
        migrations.CreateModel(
            name="Room_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room_group",
                        verbose_name="info_room",
                    ),
                ),
                (
                    "room_comment",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room_comment",
                        verbose_name="info_room_comment",
                    ),
                ),
                (
                    "room_member",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room_member",
                        verbose_name="info_room_member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room info",
                "verbose_name_plural": "Room info",
            },
        ),
        migrations.AddField(
            model_name="room_comment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="room.room_group",
                verbose_name="C_group",
            ),
        ),
    ]
