# Generated by Django 4.1 on 2022-09-22 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(verbose_name="가입날짜")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room",
                        verbose_name="room 정보",
                    ),
                ),
                (
                    "join_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="가입자",
                    ),
                ),
            ],
            options={
                "verbose_name": "room 가입자",
                "verbose_name_plural": "room 가입자목록",
                "db_table": "Room_member",
            },
        ),
    ]
