# Generated by Django 4.1 on 2022-09-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_alter_room_options_alter_room_member_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "room 리스트", "verbose_name_plural": "Room 리스트"},
        ),
        migrations.AlterModelOptions(
            name="room_comment",
            options={"verbose_name": "room 댓글", "verbose_name_plural": "room 댓글"},
        ),
        migrations.AlterModelOptions(
            name="room_member",
            options={"verbose_name": "room 유저리스트", "verbose_name_plural": "room 유저리스트"},
        ),
    ]
