# Generated by Django 4.1 on 2022-09-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_alter_room_options_alter_room_comment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room_comment",
            old_name="user",
            new_name="article",
        ),
    ]
