# Generated by Django 4.1 on 2022-09-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0005_rename_user_room_comment_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room_member",
            name="join_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="가입자",
            ),
        ),
    ]
