# Generated by Django 4.1 on 2022-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0009_alter_room_member_join_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room_comment",
            name="room",
        ),
        migrations.RemoveField(
            model_name="room_member",
            name="group",
        ),
        migrations.RemoveField(
            model_name="room_member",
            name="join_user",
        ),
        migrations.AddField(
            model_name="room",
            name="room_comment",
            field=models.ManyToManyField(to="room.room_comment", verbose_name="댓글"),
        ),
        migrations.AddField(
            model_name="room",
            name="room_member",
            field=models.ManyToManyField(to="room.room_member", verbose_name="유저리스트"),
        ),
    ]
