# Generated by Django 4.1 on 2022-09-26 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0010_remove_room_comment_room_remove_room_member_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_member",
            name="join_user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="가입자",
            ),
        ),
    ]
