# Generated by Django 4.1 on 2022-09-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0011_room_member_join_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room_comment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="room_member",
            options={},
        ),
        migrations.AlterModelTable(
            name="room_comment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="room_member",
            table=None,
        ),
    ]
