# Generated by Django 4.1 on 2022-09-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0012_alter_room_comment_options_alter_room_member_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room_member",
            name="join_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="가입자",
            ),
        ),
    ]
