# Generated by Django 4.1 on 2022-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0014_alter_room_room_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_member",
            field=models.ManyToManyField(
                blank=True, to="room.room_member", verbose_name="유저리스트"
            ),
        ),
    ]
