# Generated by Django 4.1 on 2022-09-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0016_alter_room_room_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_member",
            field=models.ManyToManyField(
                null=True, to="room.room_member", verbose_name="유저리스트"
            ),
        ),
        migrations.AlterField(
            model_name="room_member",
            name="join_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
