# Generated by Django 4.1 on 2022-09-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0018_alter_room_room_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room_member",
            name="join_user",
        ),
    ]
