# Generated by Django 4.1 on 2022-09-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0019_remove_room_member_join_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_member",
        ),
        migrations.AlterModelTable(
            name="room_comment",
            table="room_comment",
        ),
        migrations.DeleteModel(
            name="Room_member",
        ),
    ]
