# Generated by Django 4.1 on 2022-09-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0020_remove_room_room_member_alter_room_comment_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_comment",
        ),
        migrations.DeleteModel(
            name="Room_comment",
        ),
    ]
