# Generated by Django 4.1 on 2022-09-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0021_remove_room_room_comment_delete_room_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(verbose_name="가입날짜")),
                (
                    "join_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="가입자",
                    ),
                ),
            ],
            options={
                "db_table": "room_member",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_member",
            field=models.ManyToManyField(
                default="", to="room.room_member", verbose_name="유저리스트"
            ),
        ),
    ]
